import { UserRole } from '../../types/index.ts';

export type Permission =
  | 'VIEW_STOREFRONT'
  | 'CUSTOMER_CHECKOUT'
  | 'CUSTOMER_MANAGE_ACCOUNT'
  | 'MANAGE_PRODUCTS'
  | 'VIEW_INVENTORY'
  | 'MANAGE_INVENTORY'
  | 'VIEW_ORDERS'
  | 'PROCESS_ORDERS'
  | 'MANAGE_PURCHASES'
  | 'MANAGE_SUPPLIERS'
  | 'PROCESS_RETURNS'
  | 'VIEW_FINANCIALS'
  | 'MANAGE_FINANCIALS'
  | 'VIEW_REPORTS'
  | 'VIEW_ACTIVITY_LOGS'
  | 'SYSTEM_ADMINISTRATION'
  | 'MANAGE_USERS';

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  CUSTOMER: [
    'VIEW_STOREFRONT',
    'CUSTOMER_CHECKOUT',
    'CUSTOMER_MANAGE_ACCOUNT',
  ],
  CASHIER: [
    'VIEW_STOREFRONT',
    'VIEW_INVENTORY',
    'VIEW_ORDERS',
    'PROCESS_ORDERS',
  ],
  MANAGER: [
    'VIEW_STOREFRONT',
    'VIEW_INVENTORY',
    'MANAGE_INVENTORY',
    'VIEW_ORDERS',
    'PROCESS_ORDERS',
    'MANAGE_PRODUCTS',
    'MANAGE_PURCHASES',
    'MANAGE_SUPPLIERS',
    'PROCESS_RETURNS',
    'VIEW_REPORTS',
  ],
  ADMIN: [
    'VIEW_STOREFRONT',
    'VIEW_INVENTORY',
    'MANAGE_INVENTORY',
    'VIEW_ORDERS',
    'PROCESS_ORDERS',
    'MANAGE_PRODUCTS',
    'MANAGE_PURCHASES',
    'MANAGE_SUPPLIERS',
    'PROCESS_RETURNS',
    'VIEW_FINANCIALS',
    'MANAGE_FINANCIALS',
    'VIEW_REPORTS',
    'VIEW_ACTIVITY_LOGS',
    'MANAGE_USERS',
  ],
  SUPER_ADMIN: [
    'VIEW_STOREFRONT',
    'CUSTOMER_CHECKOUT',
    'CUSTOMER_MANAGE_ACCOUNT',
    'VIEW_INVENTORY',
    'MANAGE_INVENTORY',
    'VIEW_ORDERS',
    'PROCESS_ORDERS',
    'MANAGE_PRODUCTS',
    'MANAGE_PURCHASES',
    'MANAGE_SUPPLIERS',
    'PROCESS_RETURNS',
    'VIEW_FINANCIALS',
    'MANAGE_FINANCIALS',
    'VIEW_REPORTS',
    'VIEW_ACTIVITY_LOGS',
    'SYSTEM_ADMINISTRATION',
    'MANAGE_USERS',
  ],
};

export function hasPermission(role: UserRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}
